# Generated by Django 4.2.7 on 2025-08-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='admin', help_text="User's role determines their access level", max_length=10),
        ),
    ]
