# Generated by Django 4.2.7 on 2025-08-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
    ]
